apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-web-deployment
spec:
  replicas: 2 # 您可以根据需要调整副本数量
  selector:
    matchLabels:
      app: fastapi-web
  template:
    metadata:
      labels:
        app: fastapi-web
    spec:
      containers:
      - name: fastapi-web
        # 警告: 请将 'your-docker-registry/fastapi-web:latest' 替换为您的镜像地址
        # 在部署之前，您需要构建 Docker 镜像并将其推送到您的 Kubernetes 集群可以访问的镜像仓库
        image: fastapi-web:latest
        imagePullPolicy: Always # 或者 IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: fastapi-web-config
        env:
        # 使用 Secret 来加载敏感环境变量
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: fastapi-web-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: fastapi-web-secrets
              key: secret-key
        # 新增：从 Secret 加载 S3 凭证
        - name: S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: s3-endpoint-url
              optional: true # 如果您使用 AWS S3，则此项为可选
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: s3-access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: s3-secret-key
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: s3-bucket-name
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: aws-region
              optional: true # 如果您使用 MinIO 等非 AWS 服务，则此项为可选
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: fastapi-web-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-web-service
spec:
  # 使用 LoadBalancer 将服务暴露到外部。
  # 在某些环境中，您可能希望使用 NodePort 或 ClusterIP（并使用 Ingress Controller）
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: fastapi-web 